<a href="https://colab.research.google.com/github/saurav3k2/Intro-to-PyTorch/blob/main/dataset_and_dataloader_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch
from sklearn.datasets import make_classification

In [25]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [38]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [26]:
X.shape

(10, 2)

In [27]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [28]:
y.shape

(10,)

In [29]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [30]:
from torch.utils.data import Dataset, DataLoader

In [31]:
class  CustomDataset(Dataset):

  def __init__(self, features , labels):
    self.features = features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [33]:
dataset = CustomDataset(X,y)

In [35]:
len(dataset)

10

In [40]:
print(dataset[0])
print(dataset[2])
print(dataset[1])

(tensor([ 1.0683, -0.9701]), tensor(1))
(tensor([-2.8954,  1.9769]), tensor(0))
(tensor([-1.1402, -0.8388]), tensor(0))


In [49]:
dataloder = DataLoader(dataset, batch_size=2 , shuffle=True)

In [50]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [51]:
for batch_features , batch_labels in dataloder:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[1.7774, 1.5116],
        [1.8997, 0.8344]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
