<a href="https://colab.research.google.com/github/saurav3k2/Intro-to-PyTorch/blob/main/pytorch_training_pipeline_using_dataset_and_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [15]:
df.shape

(569, 33)

In [16]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [17]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

##Train test split

In [18]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,1:] , df.iloc[:, 0] , test_size = 0.2)

## scaling

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
X_train

array([[ 0.88840364,  0.42154615,  0.87804496, ...,  1.08375405,
        -0.43600089, -0.4321778 ],
       [-1.26187717, -0.56209792, -1.23248106, ..., -0.48618647,
         0.15989058,  0.78602286],
       [-0.65492911, -0.89076745, -0.66908506, ..., -0.525783  ,
        -0.20030009, -0.31889499],
       ...,
       [-0.8482063 , -1.01372296, -0.85253589, ..., -0.69747107,
         0.52506085, -0.60292291],
       [-1.22264478, -0.83874781, -1.23837168, ..., -0.94417601,
        -0.07415036, -0.11695607],
       [-0.34626256, -0.64485643, -0.40232399, ..., -0.83234675,
        -0.83436845, -1.08286989]])

In [22]:
y_train

335    M
341    B
344    B
206    B
51     B
      ..
260    M
442    B
381    B
273    B
69     B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [23]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [24]:
y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,

## Numpy array to PyTorch tensors

In [25]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [26]:
X_train_tensor

tensor([[ 0.8884,  0.4215,  0.8780,  ...,  1.0838, -0.4360, -0.4322],
        [-1.2619, -0.5621, -1.2325,  ..., -0.4862,  0.1599,  0.7860],
        [-0.6549, -0.8908, -0.6691,  ..., -0.5258, -0.2003, -0.3189],
        ...,
        [-0.8482, -1.0137, -0.8525,  ..., -0.6975,  0.5251, -0.6029],
        [-1.2226, -0.8387, -1.2384,  ..., -0.9442, -0.0742, -0.1170],
        [-0.3463, -0.6449, -0.4023,  ..., -0.8323, -0.8344, -1.0829]])

In [27]:
y_train_tensor.shape

torch.Size([455])

In [29]:
from torch.utils.data import Dataset , DataLoader

In [33]:
class CustomDataset(Dataset):
  def __init__(self, features , labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index] , self.labels[index]

In [34]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [35]:
train_dataset[10]

(tensor([ 1.4942,  1.7457,  1.4839,  1.4608,  0.3920,  0.8292,  1.3878,  1.3259,
          0.3251, -0.0997,  0.8999, -0.4182,  0.7932,  0.7226,  0.0899, -0.0509,
          0.2541,  0.1791, -0.7663, -0.1350,  1.5791,  1.7123,  1.6125,  1.5158,
          1.9832,  0.8672,  1.4946,  1.1534,  0.6180,  0.7286]),
 tensor(1.))

In [36]:
train_loader = DataLoader(train_dataset, batch_size=32 , shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32 , shuffle=True)

## Defining the model

In [48]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features , 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out) # Corrected: apply sigmoid to the output of the linear layer

    return out

Important Parameters

In [42]:
learning_rate = 0.1
epochs =25

In [50]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

## Define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

## Define loss function
loss_function = nn.BCELoss()

Training Pipeline

In [54]:
## Define loop
for epoch in range(epochs):
  for batch_features , batch_labels in train_loader:

    ## forward pass
    y_pred = model(batch_features)

    ## Loss calculation
    loss  = loss_function(y_pred ,batch_labels.view(-1,1))

    ## clear gradients
    optimizer.zero_grad()

    ## Backward pass
    loss.backward()

    ## parameters upadate
    optimizer.step()

    ## print loss in each epoch
    print(f"Epoch : {epoch +1 } , Loss : {loss.item()}")

Epoch : 1 , Loss : 0.15760499238967896
Epoch : 1 , Loss : 0.04595593363046646
Epoch : 1 , Loss : 0.050321854650974274
Epoch : 1 , Loss : 0.03301399573683739
Epoch : 1 , Loss : 0.04891258850693703
Epoch : 1 , Loss : 0.07138218730688095
Epoch : 1 , Loss : 0.08333520591259003
Epoch : 1 , Loss : 0.04532746225595474
Epoch : 1 , Loss : 0.20743371546268463
Epoch : 1 , Loss : 0.04610889405012131
Epoch : 1 , Loss : 0.1678597778081894
Epoch : 1 , Loss : 0.08651258796453476
Epoch : 1 , Loss : 0.05955220013856888
Epoch : 1 , Loss : 0.021032683551311493
Epoch : 1 , Loss : 0.09672634303569794
Epoch : 2 , Loss : 0.10328370332717896
Epoch : 2 , Loss : 0.04084198176860809
Epoch : 2 , Loss : 0.021885087713599205
Epoch : 2 , Loss : 0.04004205763339996
Epoch : 2 , Loss : 0.25892797112464905
Epoch : 2 , Loss : 0.04778748378157616
Epoch : 2 , Loss : 0.039825908839702606
Epoch : 2 , Loss : 0.022104710340499878
Epoch : 2 , Loss : 0.045760106295347214
Epoch : 2 , Loss : 0.0898747444152832
Epoch : 2 , Loss : 0.