<a href="https://colab.research.google.com/github/saurav3k2/Intro-to-PyTorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Plan Of Action
 - Revision
 - Improvements   
 - The NN module
 - The torch.optim module

 #### Improvement
  - Building the neural network using nn module
  - Using built-in activation function
  - Using built-in loss function
  - Using built-in optimizer

In [7]:
## Create model class
import torch
import torch.nn as nn


class Model(nn.Module):
  def __init__(self  , num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features , 3),
        nn.ReLU(),
        nn.Linear(3 , 1) ,
        nn.Sigmoid()
    )

  def forward(self , features):
    out = self.network(features)
    return  out

In [8]:
## create a dataset
features  = torch.rand(10,5)

## Create  model
model = Model(features.shape[1])

## call model for forward pass
## Model.forward(features)
model(features)

tensor([[0.5668],
        [0.5962],
        [0.5686],
        [0.5646],
        [0.5898],
        [0.5667],
        [0.5760],
        [0.5658],
        [0.5819],
        [0.5573]], grad_fn=<SigmoidBackward0>)

In [11]:
## show model weights
model.network[2].weight

Parameter containing:
tensor([[ 0.1144, -0.4069,  0.5123]], requires_grad=True)

In [12]:
## show model bias
model.network[2].bias

Parameter containing:
tensor([0.2224], requires_grad=True)

In [13]:
!pip install torchinfo

In [15]:
from torchinfo import summary
summary(model , input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00